<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LyDT-Phoenix" failures="1" tests="7" name="ProjectEnas.CF210_Website" time="24.268" errors="0" timestamp="29 Dec 2023 13:34:30 GMT" skipped="0">
  <testcase classname="ProjectEnas.CF210_Website" name="TC_04_Check_change_value_Sample_Explanation" time="1.427"/>
  <testcase classname="ProjectEnas.CF210_Website" name="TC01b_Check_UI_Form" time="0.178">
    <failure message="expected [#333D5A] but found [#000000]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [#333D5A] but found [#000000]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at ProjectEnas.CF210_Website.TC01b_Check_UI_Form(CF210_Website.java:89)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC01b_Check_UI_Form -->
  <testcase classname="ProjectEnas.CF210_Website" name="TC_05_Check_change_value_General_Explanation" time="2.962"/>
  <testcase classname="ProjectEnas.CF210_Website" name="TC_06_Check_change_value_Additional_Explanation" time="3.034"/>
  <testcase classname="ProjectEnas.CF210_Website" name="TC01a_Check_UI_Menu" time="8.411"/>
  <testcase classname="ProjectEnas.CF210_Website" name="TC02_Click_On_Switch_Required" time="5.255"/>
  <testcase classname="ProjectEnas.CF210_Website" name="TC_03_Check_change_value_Title_Component" time="3.001"/>
</testsuite> <!-- ProjectEnas.CF210_Website -->
